module.exports.userobject = [{
  id: 2,
  googleid: '1334jgajagjg02',
  firstname: 'joey',
  lastname: 'delahoussaye',
  bio: 'austin',
  followercount: 5,
  followingcount: 7,
  djactive: false,
  followers: [3, 4, 6],
  following: [4, 8],
},
{
  id: 3,
  googleid: '1312534jgajagjg02',
  firstname: 'jason',
  lastname: 'delahoussaye',
  bio: 'austin',
  followercount: 5,
  followingcount: 7,
  djactive: false,
  followers: [3, 4, 6],
  following: [4, 8],
},
{
  id: 4,
  googleid: '1334j123gajagjg02',
  firstname: 'Josh',
  lastname: 'delahoussaye',
  bio: 'austin',
  followercount: 5,
  followingcount: 7,
  djactive: false,
  followers: [3, 4, 6],
  following: [4, 8],
},
{
  id: 5,
  googleid: '133d4jgajagjg02',
  firstname: 'Jimmy',
  lastname: 'delahoussaye',
  bio: 'austin',
  followercount: 5,
  followingcount: 7,
  djactive: false,
  followers: [3, 4, 6],
  following: [4, 8],
},
{
  id: 6,
  googleid: '1334jgajagjg02',
  firstname: 'James',
  lastname: 'delahoussaye',
  bio: 'austin',
  followercount: 5,
  followingcount: 7,
  djactive: false,
  followers: [3, 4, 6],
  following: [4, 8],
},
]
